version: '3.8'

services:
  api-service:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./files:/app/files
      - ./model/saved_models:/app/model/saved_models
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          cpus: '2'
        reservations:
          cpus: '1'