version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: src/Dockerfile
    volumes:
      - ../files:/app/files
      - ../model/saved_models:/app/model/saved_models
      - ../files:/app/test_files
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MINIO_HOST=minio
      - MINIO_PORT=9000
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - minio
      - worker
  
  worker:
    build:
      context: ..
      dockerfile: src/Dockerfile
    command: python -m src.worker.worker
    volumes:
      - ../files:/app/files
      - ../model/saved_models:/app/model/saved_models
      - ../files:/app/test_files
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MINIO_HOST=minio
      - MINIO_PORT=9000
    depends_on:
      - rabbitmq
      - minio
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 10
  
  minio:
    image: minio/minio
    volumes:
      - ../minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3 